In [1]:
##### Categories to classify into: BUSINESS, ENTERTAINMENT, HEALTH, SCIENCE, SPORTS, TECH, U.S. NEWS, WORLD NEWS

###### Data from "RishabhMisraHuffPostDataset" & "GoogleNewsDataset"

###### BUSINESS - 13444
###### Entertainment - 9163
###### HEALTH - 6694
###### SCIENCE - 6565
###### SPORTS - 13306
###### TECH - 9037
###### U.S. NEWS - 6377
###### WORLD NEWS - 10328
###### Total - 74914

In [2]:
import pandas as pd
df = pd.read_csv("../data/6TrainingData.csv")
df

,_id,category,headline
0,65583f2abf0ca14ca2d80f26,HEALTH,To The People Who Say ‘I’m Tired’ When Someone...
1,65583f2abf0ca14ca2d80f99,HEALTH,Eating Shake Shack Made Me Feel Healthier Than...
2,65583f2abf0ca14ca2d80fcf,HEALTH,How To Stay Updated On The News Without Losing...
3,65583f2abf0ca14ca2d81083,HEALTH,27 Perfect Tweets About Whole30 That Will Make...
4,65583f2abf0ca14ca2d8108a,HEALTH,The Real Reason Your Hands Are Always Cold
...,...,...,...
74909,65591704853abc543478a77c,U.S. NEWS,MSP executive seeks meeting with TSA over airp...
74910,65591704853abc543478a77d,U.S. NEWS,Free Community Health Clinic For Austin Reside...
74911,65591704853abc543478a783,U.S. NEWS,"Mover packs up client, finds out client is the..."
74912,65591704853abc543478a78f,U.S. NEWS,Detentions of Child Migrants at the U.S. Borde...
74913,65591704853abc543478a7a0,U.S. NEWS,Here are Baltimore's top 4 Japanese spots

In [3]:
df.drop(columns=["_id"], inplace=True)
df

        category                                           headline
0         HEALTH  To The People Who Say ‘I’m Tired’ When Someone...
1         HEALTH  Eating Shake Shack Made Me Feel Healthier Than...
2         HEALTH  How To Stay Updated On The News Without Losing...
3         HEALTH  27 Perfect Tweets About Whole30 That Will Make...
4         HEALTH         The Real Reason Your Hands Are Always Cold
...          ...                                                ...
74909  U.S. NEWS  MSP executive seeks meeting with TSA over airp...
74910  U.S. NEWS  Free Community Health Clinic For Austin Reside...
74911  U.S. NEWS  Mover packs up client, finds out client is the...
74912  U.S. NEWS  Detentions of Child Migrants at the U.S. Borde...
74913  U.S. NEWS          Here are Baltimore's top 4 Japanese spots

[74914 rows x 2 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
label = le.fit_transform(df["category"])

df.drop(columns=["category"], inplace=True)

df["category"] = label
df

                                                headline  category
0      To The People Who Say ‘I’m Tired’ When Someone...         2
1      Eating Shake Shack Made Me Feel Healthier Than...         2
2      How To Stay Updated On The News Without Losing...         2
3      27 Perfect Tweets About Whole30 That Will Make...         2
4             The Real Reason Your Hands Are Always Cold         2
...                                                  ...       ...
74909  MSP executive seeks meeting with TSA over airp...         6
74910  Free Community Health Clinic For Austin Reside...         6
74911  Mover packs up client, finds out client is the...         6
74912  Detentions of Child Migrants at the U.S. Borde...         6
74913          Here are Baltimore's top 4 Japanese spots         6

[74914 rows x 2 columns]

In [5]:
import en_core_web_lg

nlp = en_core_web_lg.load()

def nlpify(text):
    text = str(text)
    return nlp(text).vector

df["headline"] = df["headline"].apply(nlpify)

In [6]:
df

                                                headline  category
0      [0.37533942, 0.95536953, -0.74450433, -3.20085...         2
1      [0.3806063, -0.2258882, -1.0344046, -0.5882237...         2
2      [1.7622063, 0.19124928, -2.59872, -1.8299657, ...         2
3      [0.030336391, -0.96273106, -1.6066481, -1.4785...         2
4      [-0.41738123, 1.1906976, 0.17487374, 2.0997024...         2
...                                                  ...       ...
74909  [-0.4634022, 0.169612, -1.1760511, 1.791229, 2...         6
74910  [0.08683337, -2.0036366, 1.1488711, 1.3109378,...         6
74911  [-0.9640431, 0.37724832, -1.588968, 0.83171546...         6
74912  [-1.9374765, 0.57632, -1.6914653, 2.0595186, 4...         6
74913  [-0.49974996, 0.2151987, -1.9404237, 1.6130887...         6

[74914 rows x 2 columns]

In [7]:
from sklearn.model_selection import train_test_split

X = df["headline"]
y = df["category"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [8]:
import numpy as np

X_train_2d = np.stack(X_train)
X_test_2d = np.stack(X_test)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

logisticregression = LogisticRegression()
logisticregression.fit(X_train_2d, y_train)

y_pred = logisticregression.predict(X_test_2d)

classification_repo = classification_report(y_true=y_test, y_pred=y_pred, target_names=["BUSINESS", "ENTERTAINMENT",  "HEALTH", "SCIENCE", "SPORTS", "TECH", "U.S. NEWS", "WORLD NEWS"])
print(classification_repo)

/usr/local/python/3.12.0/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

               precision    recall  f1-score   support

     BUSINESS       0.72      0.73      0.73      4029
ENTERTAINMENT       0.76      0.79      0.78      2694
       HEALTH       0.70      0.75      0.73      1965
      SCIENCE       0.82      0.80      0.81      2004
       SPORTS       0.87      0.87      0.87      4077
         TECH       0.80      0.78      0.79      2725
    U.S. NEWS       0.69      0.64      0.67      1860
   WORLD NEWS       0.84      0.84      0.84      3121

     accuracy                           0.78     22475
    macro avg       0.78      0.78      0.78     22475
 weighted avg       0.78      0.78      0.78     22475

In [10]:
logisticregression2 = LogisticRegression(class_weight="balanced")
logisticregression2.fit(X_train_2d, y_train)

y_pred2 = logisticregression2.predict(X_test_2d)

classification_repo2 = classification_report(y_true=y_test, y_pred=y_pred2, target_names=["BUSINESS", "ENTERTAINMENT", "HEALTH", "SCIENCE", "SPORTS", "TECH", "U.S. NEWS", "WORLD NEWS"])
print(classification_repo2)

               precision    recall  f1-score   support

     BUSINESS       0.79      0.65      0.71      4029
ENTERTAINMENT       0.75      0.80      0.77      2694
       HEALTH       0.64      0.81      0.71      1965
      SCIENCE       0.78      0.82      0.80      2004
       SPORTS       0.90      0.83      0.87      4077
         TECH       0.79      0.79      0.79      2725
    U.S. NEWS       0.61      0.72      0.66      1860
   WORLD NEWS       0.85      0.82      0.84      3121

     accuracy                           0.78     22475
    macro avg       0.76      0.78      0.77     22475
 weighted avg       0.78      0.78      0.78     22475

/usr/local/python/3.12.0/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(